# Generated by Django 3.1.2 on 2020-10-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_buy_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='pin',
            field=models.CharField(default='', max_length=70),
        ),
    ]
