# Generated by Django 3.1.2 on 2020-10-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_buy_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
