# Generated by Django 3.1.2 on 2020-10-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201025_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
