# Generated by Django 3.1.2 on 2020-10-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_description4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description5',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
