# Generated by Django 3.1.2 on 2020-10-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_description6'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description7',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
