# Generated by Django 3.1.2 on 2020-10-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20201025_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description8',
        ),
    ]
