# Generated by Django 3.1.2 on 2020-11-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='product_detail',
            field=models.CharField(default='', max_length=70),
        ),
    ]
