# Generated by Django 3.1.2 on 2020-11-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_buy_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='product_detail1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buy',
            name='product_detail2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='buy',
            name='product_detail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
