# Generated by Django 3.1.2 on 2020-11-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20201101_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='price',
            field=models.CharField(default='', max_length=70),
        ),
    ]
