# Generated by Django 3.1.2 on 2020-11-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_buy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='product_detail2',
        ),
    ]
