# Generated by Django 3.1.2 on 2020-12-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_buy_product_detail2'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
